version: 2 

sources: 
  - name: raw
    schema: gz_raw_data
    description: this is the raw date we are using
    tables:
      - name:  product
        identifier: raw_gz_product
        description: table des produits
      - name: sales
        identifier : raw_gz_sales
        description: tables des ventes
      - name: ship
        identifier: raw_gz_ship
        description: tables des frais liés aux commandes
