version: 2 

sources: 
  - name: gz_raw_data
    schema: raw
    description: this is the raw date we are using
    tables:
      - identifier: raw_gz_product
        name:  product
        description: table des produits
      - identifier : raw_gz_sales
        name: sales
        description: tables des ventes
      - identifier: raw_gz_ship
        name: ship
        description: tables des frais liés aux commandes
